package com.openclassrooms.magicgithub.api;

import com.openclassrooms.magicgithub.model.User;

import java.util.List;

import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.FAKE_USERS;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.FAKE_USERS_RANDOM;
import static com.openclassrooms.magicgithub.api.FakeApiServiceGenerator.generateUsers;

public class FakeApiService implements ApiService {

    private List<User> users = generateUsers();

    /**
     * Return a list of {@link User}
     * Those users must be generated by {@link FakeApiServiceGenerator}
     * @return
     */
    @Override
    public List<User> getUsers() {
        // TODO: A modifier
        /**List<User> lesUsers = FAKE_USERS;
        for (User user : lesUsers) {
        }
        return lesUsers;
        */
        //users.addAll(generateUsers());
        //users.addAll(FAKE_USERS);

        //System.out.println("getUsers FakeApiService" + users.toString());

        //List<User> liste= FAKE_USERS;
        //return liste;
        return users;
        //return FAKE_USERS;

       //return null;

        // instancie generateUsers de FakeApiServiceGenerator
        /*if (users!=null) {
            return users;
        }
        else
        return null;*/
    }

    /**
     * Generate a random {@link User} and add it {@link FakeApiService#users} list.
     * This user must be get from the {@link FakeApiServiceGenerator#FAKE_USERS_RANDOM} list.
     */
    @Override
    public void generateRandomUser() {
        // TODO: A modifier
        FAKE_USERS_RANDOM.toArray();
    }

    /**
     * Delete a {@link User} from the {@link FakeApiService#users} list.
     */
    @Override
    public void deleteUser(User user) {
        // TODO: A modifier
        //user=null;
        //this.deleteUser(user);
        //deleteUser(user);
        users.remove(user);


    }
}
